version: "3.9"

services:
  streamlit:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env  # Monta o arquivo .env no container
    environment:
      - PYTHONUNBUFFERED=1
